services:
  - type: web
    name: youtube-media-fetcher
    env: python
    plan: free # Or your desired plan
    buildCommand: "sudo apt-get clean && sudo rm -rf /var/lib/apt/lists/* && sudo apt-get update && sudo apt-get install -y --allow-releaseinfo-change ffmpeg && pip install -r requirements.txt"
    startCommand: "gunicorn app:app --timeout 120"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.5
      - key: FLASK_ENV
        value: production